server :
   port: 9094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ecom:
  amqp:
    rabbit:
      address: localhost:5672
      username: guest
      password: guest
      vhost: /
      exchange: Ecom-exchange
      queue: Ecom-history-queue

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecom



      